# Summary

Crawl a bunch of sites and save data to BQ

In [1]:
import sys, os, io

import pandas as pd
from tqdm import tqdm

# Web crawling and scraping tools class
sys.path.insert(0, "crawl_tools/")
import web_scraper as ws
import webfile_downloader as wfd
import web_crawler as wc

from google.cloud import storage

# from google.cloud.bigquery.client import pandas
# from google.oauth2 import service_account
# import pandas_gbq
# sys.path.insert(0, "../../interface/utils/")
# import authentication as au
# import asyncio
# import numpy as np

## Test the site scraper on one site

In [2]:
# turl = "https://en.wikipedia.org/wiki/Chaffey_College"
# turl = "https://asdjhfbads.jhbf"
# turl = "https://www.cccco.edu/"
turl = "https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx?year=2023&surveyNumber=-1&sid=e74260c9-5075-4103-bb77-fe58fc4c96f8&rtid=7"
turl = "https://www.ecs.org"

turl = "https://www.ecs.org/events/"

test = await ws.webScraper.visit_page(url=turl)

test.crawl_results.keys()
# type(test.crawl_results)

# print(test.crawl_results['atag_urls'])
# [u for u in test.crawl_results['atag_urls'] if u.find(".zip")>=0]
# test.crawl_results['ptag_text']

dict_keys([])

## Test file downloader on one site

In [2]:

turl = "https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx?year=2023&surveyNumber=-1&sid=e74260c9-5075-4103-bb77-fe58fc4c96f8&rtid=7"
turl = "https://www.cccco.edu"
turl = "https://en.wikipedia.org/wiki/Chaffey_College"
turl =  'https://nces.ed.gov/ipeds/datacenter/data/C2023DEP_Data_Stata.zip'
# turl = "https://www.cccco.edu/-/media/CCCCO-Website/docs/general/cccco-webinar-summary-october-2024-a11y.pdf"
turl = "https://www.cccco.edu/-/media/CCCCO-Website/docs/guided-pathways/guided-pathways-expenditure-guidelines-a11y.pdf"
# creds = au.ApiAuthentication()

# Google
# os.environ["GOOGLE_API_KEY"] = creds.apis_configs["GOOGLE_API_KEY"]

# Note this downloads to a GCP bucket
test = wfd.webFileDownloader(url=turl)
test.download_document()

1

## Set up crawl parameters

In [4]:

dupath = "../../../ccc_policy_assistant/code/sprints/embeddings_gcp"
sys.path.insert(0, dupath)
import url_exclusion_list as uel
# from urllib.parse import urlparse

wiki_dont_crawl = uel.exclude_urls

lao_urls= ["https://lao.ca.gov/Publications/Report/4531",
            "https://lao.ca.gov/Publications/Report/4853",
            "https://lao.ca.gov/Publications/Report/4664",
            "https://lao.ca.gov/Publications/Report/4913"
            ]

ecs_dont_crawl = ['www.ecs.org/state/al/', 'www.ecs.org/state/ky/', 'www.ecs.org/state/oh/', 'www.ecs.org/state/ak/', 'www.ecs.org/state/la/', 'www.ecs.org/state/ok/', 'www.ecs.org/state/az/', 'www.ecs.org/state/me/', 'www.ecs.org/state/or/', 'www.ecs.org/state/ar/', 'www.ecs.org/state/md/', 'www.ecs.org/state/pa/', 'www.ecs.org/state/as/', 'www.ecs.org/state/ma/', 'www.ecs.org/state/pr/', 'www.ecs.org/state/mi/', 'www.ecs.org/state/ri/', 'www.ecs.org/state/co/', 'www.ecs.org/state/mn/', 'www.ecs.org/state/sc/', 'www.ecs.org/state/ct/', 'www.ecs.org/state/ms/', 'www.ecs.org/state/sd/', 'www.ecs.org/state/de/', 'www.ecs.org/state/mo/', 'www.ecs.org/state/tn/', 'www.ecs.org/state/dc/', 'www.ecs.org/state/mt/', 'www.ecs.org/state/tx/', 'www.ecs.org/state/fl/', 'www.ecs.org/state/ne/', 'www.ecs.org/state/tt/', 'www.ecs.org/state/ga/', 'www.ecs.org/state/nv/', 'www.ecs.org/state/ut/', 'www.ecs.org/state/gu/', 'www.ecs.org/state/nh/', 'www.ecs.org/state/vt/', 'www.ecs.org/state/hi/', 'www.ecs.org/state/nj/', 'www.ecs.org/state/va/', 'www.ecs.org/state/id/', 'www.ecs.org/state/nm/', 'www.ecs.org/state/vi/', 'www.ecs.org/state/il/', 'www.ecs.org/state/ny/', 'www.ecs.org/state/wa/', 'www.ecs.org/state/in/', 'www.ecs.org/state/nc/', 'www.ecs.org/state/wv/', 'www.ecs.org/state/ia/', 'www.ecs.org/state/nd/', 'www.ecs.org/state/wi/', 'www.ecs.org/state/ks/', 'www.ecs.org/state/mp/', 'www.ecs.org/state/wy/', 'www.ecs.org/state/al/#dropdown', 'www.ecs.org/state/ky/#dropdown', 'www.ecs.org/state/oh/#dropdown', 'www.ecs.org/state/ak/#dropdown', 'www.ecs.org/state/la/#dropdown', 'www.ecs.org/state/ok/#dropdown', 'www.ecs.org/state/az/#dropdown', 'www.ecs.org/state/me/#dropdown', 'www.ecs.org/state/or/#dropdown', 'www.ecs.org/state/ar/#dropdown', 'www.ecs.org/state/md/#dropdown', 'www.ecs.org/state/pa/#dropdown', 'www.ecs.org/state/as/#dropdown', 'www.ecs.org/state/ma/#dropdown', 'www.ecs.org/state/pr/#dropdown', 'www.ecs.org/state/mi/#dropdown', 'www.ecs.org/state/ri/#dropdown', 'www.ecs.org/state/co/#dropdown', 'www.ecs.org/state/mn/#dropdown', 'www.ecs.org/state/sc/#dropdown', 'www.ecs.org/state/ct/#dropdown', 'www.ecs.org/state/ms/#dropdown', 'www.ecs.org/state/sd/#dropdown', 'www.ecs.org/state/de/#dropdown', 'www.ecs.org/state/mo/#dropdown', 'www.ecs.org/state/tn/#dropdown', 'www.ecs.org/state/dc/#dropdown', 'www.ecs.org/state/mt/#dropdown', 'www.ecs.org/state/tx/#dropdown', 'www.ecs.org/state/fl/#dropdown', 'www.ecs.org/state/ne/#dropdown', 'www.ecs.org/state/tt/#dropdown', 'www.ecs.org/state/ga/#dropdown', 'www.ecs.org/state/nv/#dropdown', 'www.ecs.org/state/ut/#dropdown', 'www.ecs.org/state/gu/#dropdown', 'www.ecs.org/state/nh/#dropdown', 'www.ecs.org/state/vt/#dropdown', 'www.ecs.org/state/hi/#dropdown', 'www.ecs.org/state/nj/#dropdown', 'www.ecs.org/state/va/#dropdown', 'www.ecs.org/state/id/#dropdown', 'www.ecs.org/state/nm/#dropdown', 'www.ecs.org/state/vi/#dropdown', 'www.ecs.org/state/il/#dropdown', 'www.ecs.org/state/ny/#dropdown', 'www.ecs.org/state/wa/#dropdown', 'www.ecs.org/state/in/#dropdown', 'www.ecs.org/state/nc/#dropdown', 'www.ecs.org/state/wv/#dropdown', 'www.ecs.org/state/ia/#dropdown', 'www.ecs.org/state/nd/#dropdown', 'www.ecs.org/state/wi/#dropdown', 'www.ecs.org/state/ks/#dropdown', 'www.ecs.org/state/mp/#dropdown', 'www.ecs.org/state/wy/#dropdown']

cpdat = [{"seed_url": "https://en.wikipedia.org/wiki/California_Community_Colleges",
  "storage_folder": "wikipedia",
  "crawl_urls": "",
  "dont_crawl_urls": ";".join(wiki_dont_crawl),
  "crawl_depth": 10,
  "crawl_width": 30},

 {"seed_url": "https://www.cccco.edu",
  "storage_folder": "cccco",
  "crawl_urls": "",
  "dont_crawl_urls": "",
  "crawl_depth": 10,
  "crawl_width": 30},

  {"seed_url": "https://www.ccleague.org",
  "storage_folder": "ccleague",
   "crawl_urls": "",
  "dont_crawl_urls": "",
  "crawl_depth": 10,
  "crawl_width": 30},

   {"seed_url": "https://cccaoe.org/",
  "storage_folder": "cccaoe",
    "crawl_urls": "",
  "dont_crawl_urls": "",
  "crawl_depth": 10,
  "crawl_width": 30},

   {"seed_url": "https://lao.ca.gov/Publications/",
    "storage_folder": "lao",
    "crawl_urls":";".join(lao_urls),
    "dont_crawl_urls": "",
    "crawl_depth": 1,
    "crawl_width": 10},

   {"seed_url": "https://cccaoe.org/",
    "storage_folder": "cccaoe",
    "crawl_urls":"",
    "dont_crawl_urls": "",
    "crawl_depth": 10,
    "crawl_width": 30},

   {"seed_url": "https://ccrc.tc.columbia.edu/",
    "storage_folder": "columbia",
    "crawl_urls":"",
    "dont_crawl_urls": "",
    "crawl_depth": 10,
    "crawl_width": 30},

   {"seed_url": "https://nscresearchcenter.org/",
    "storage_folder": "nsc",
    "crawl_urls":"",
    "dont_crawl_urls": "",
    "crawl_depth": 10,
    "crawl_width": 30},

    {"seed_url": "https://www.aacc.nche.edu/",
    "storage_folder": "aacc",
    "crawl_urls":"",
    "dont_crawl_urls": "",
    "crawl_depth": 10,
    "crawl_width": 30}   ,

    {"seed_url": "https://www.ecs.org/",
    "storage_folder": "ecs",
    "crawl_urls":"",
    "dont_crawl_urls": ";".join(ecs_dont_crawl),
    "crawl_depth": 10,
    "crawl_width": 30}

         ]

cp_filename = "crawl_configuraton.csv"
cp_path = "../data/crawl_params"
df_cp = pd.DataFrame(data=cpdat)

# df_cp.to_csv(os.path.join(cp_path, cp_filename), index=False)

df_cp

,seed_url,storage_folder,crawl_urls,dont_crawl_urls,crawl_depth,crawl_width
0,https://en.wikipedia.org/wiki/California_Commu...,wikipedia,,https://en.wikipedia.org/wiki/File:CDI-Seal-Co...,10,30
1,https://www.cccco.edu,cccco,,,10,30
2,https://www.ccleague.org,ccleague,,,10,30
3,https://cccaoe.org/,cccaoe,,,10,30
4,https://lao.ca.gov/Publications/,lao,https://lao.ca.gov/Publications/Report/4531;ht...,,1,10
5,https://cccaoe.org/,cccaoe,,,10,30
6,https://ccrc.tc.columbia.edu/,columbia,,,10,30
7,https://nscresearchcenter.org/,nsc,,,10,30
8,https://www.aacc.nche.edu/,aacc,,,10,30
9,https://www.ecs.org/,ecs,,www.ecs.org/state/al/;www.ecs.org/state/ky/;ww...,10,30

## Web Crawler

## Crawl websites (and write results to GCS)

In [2]:
# Read crawl parameters
cp_filename = "crawl_configuraton.csv"
cp_path = "../data/crawl_params"
df_cp = pd.read_csv(filepath_or_buffer=os.path.join(cp_path, cp_filename))
df_cp = df_cp.fillna(" ")

df_cp

,seed_url,storage_folder,crawl_urls,dont_crawl_urls,crawl_depth,crawl_width
0,https://en.wikipedia.org/wiki/California_Commu...,wikipedia,,https://en.wikipedia.org/wiki/File:CDI-Seal-Co...,10,30
1,https://www.cccco.edu,cccco,,,10,30
2,https://www.ccleague.org,ccleague,,,10,30
3,https://cccaoe.org/,cccaoe,,,10,30
4,https://lao.ca.gov/Publications/,lao,https://lao.ca.gov/Publications/Report/4531;ht...,,1,10
5,https://cccaoe.org/,cccaoe,,,10,30
6,https://ccrc.tc.columbia.edu/,columbia,,,10,30
7,https://nscresearchcenter.org/,nsc,,,10,30
8,https://www.aacc.nche.edu/,aacc,,,10,30
9,https://www.ecs.org/,ecs,,www.ecs.org/state/al/;www.ecs.org/state/ky/;ww...,10,30

In [3]:
# Crawl seed_url and web links found on it and its child pages
dont_crawl_urls = []

for idx in tqdm(df_cp.index):

    crawler = wc.webCrawler(seed_url=df_cp.loc[idx, "seed_url"],
                            gcs_directory=df_cp.loc[idx, "storage_folder"])
    crlres = await crawler.crawl_sites(dont_crawl_urls=df_cp.loc[idx, "dont_crawl_urls"].split(";"),
                                       crawl_urls=df_cp.loc[idx, "crawl_urls"].split(";"),
                                       depth=df_cp.loc[idx, "crawl_depth"],
                                       width=df_cp.loc[idx, "crawl_width"])

  0%|          | 0/10 [00:00<?, ?it/s]
  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:02<00:25,  2.82s/it]

Depth level finished: 1: 1 URLs crawled; 0 files downloaded; 544 URLs in to_crawl_urls; 651 URLs in dont_crawl_urls

 20%|██        | 2/10 [01:13<05:41, 42.74s/it]

Depth level finished: 2: 28 URLs crawled; 0 files downloaded; 2451 URLs in to_crawl_urls; 714 URLs in dont_crawl_urls

 30%|███       | 3/10 [02:16<06:04, 52.08s/it]

Depth level finished: 3: 52 URLs crawled; 0 files downloaded; 7803 URLs in to_crawl_urls; 780 URLs in dont_crawl_urls

 40%|████      | 4/10 [03:25<05:53, 58.83s/it]

Depth level finished: 4: 79 URLs crawled; 0 files downloaded; 14744 URLs in to_crawl_urls; 843 URLs in dont_crawl_urls
Batch 1 saved to disk

 50%|█████     | 5/10 [04:32<05:08, 61.63s/it]

Depth level finished: 5: 104 URLs crawled; 0 files downloaded; 15337 URLs in to_crawl_urls; 908 URLs in dont_crawl_urls

 60%|██████    | 6/10 [05:48<04:25, 66.40s/it]

Depth level finished: 6: 131 URLs crawled; 0 files downloaded; 20640 URLs in to_crawl_urls; 971 URLs in dont_crawl_urls

 70%|███████   | 7/10 [06:39<03:04, 61.62s/it]

Depth level finished: 7: 154 URLs crawled; 0 files downloaded; 21065 URLs in to_crawl_urls; 1038 URLs in dont_crawl_urls

 80%|████████  | 8/10 [07:45<02:05, 62.84s/it]

Depth level finished: 8: 180 URLs crawled; 0 files downloaded; 20182 URLs in to_crawl_urls; 1102 URLs in dont_crawl_urls
Batch 2 saved to disk

 90%|█████████ | 9/10 [08:46<01:02, 62.40s/it]

Depth level finished: 9: 203 URLs crawled; 0 files downloaded; 12799 URLs in to_crawl_urls; 1169 URLs in dont_crawl_urls

100%|██████████| 10/10 [09:57<00:00, 59.73s/it]

Depth level finished: 10: 231 URLs crawled; 0 files downloaded; 14078 URLs in to_crawl_urls; 1231 URLs in dont_crawl_urls

 10%|█         | 1/10 [09:58<1:29:43, 598.16s/it]

Batch 3 saved to disk

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:03<00:27,  3.06s/it]

Depth level finished: 1: 1 URLs crawled; 0 files downloaded; 43 URLs in to_crawl_urls; 6 URLs in dont_crawl_urls

 20%|██        | 2/10 [01:14<05:46, 43.30s/it]

Depth level finished: 2: 24 URLs crawled; 0 files downloaded; 222 URLs in to_crawl_urls; 73 URLs in dont_crawl_urls

 30%|███       | 3/10 [02:18<06:08, 52.61s/it]

Depth level finished: 3: 42 URLs crawled; 4 files downloaded; 302 URLs in to_crawl_urls; 141 URLs in dont_crawl_urls

 40%|████      | 4/10 [03:30<06:01, 60.22s/it]

Depth level finished: 4: 68 URLs crawled; 5 files downloaded; 306 URLs in to_crawl_urls; 204 URLs in dont_crawl_urls

 50%|█████     | 5/10 [04:58<05:52, 70.43s/it]

Depth level finished: 5: 89 URLs crawled; 8 files downloaded; 433 URLs in to_crawl_urls; 270 URLs in dont_crawl_urls

 60%|██████    | 6/10 [05:39<04:00, 60.21s/it]

Depth level finished: 6: 99 URLs crawled; 24 files downloaded; 55 URLs in to_crawl_urls; 334 URLs in dont_crawl_urls

 70%|███████   | 7/10 [06:50<03:11, 63.94s/it]

Depth level finished: 7: 123 URLs crawled; 30 files downloaded; 113 URLs in to_crawl_urls; 394 URLs in dont_crawl_urls

 80%|████████  | 8/10 [07:48<02:03, 61.86s/it]

Depth level finished: 8: 143 URLs crawled; 32 files downloaded; 345 URLs in to_crawl_urls; 462 URLs in dont_crawl_urls
Batch 1 saved to disk

 90%|█████████ | 9/10 [08:27<00:54, 54.73s/it]

Depth level finished: 9: 159 URLs crawled; 34 files downloaded; 54 URLs in to_crawl_urls; 534 URLs in dont_crawl_urls

100%|██████████| 10/10 [10:00<00:00, 60.01s/it]

Depth level finished: 10: 178 URLs crawled; 40 files downloaded; 525 URLs in to_crawl_urls; 599 URLs in dont_crawl_urls

 20%|██        | 2/10 [19:58<1:19:56, 599.52s/it]

Batch 2 saved to disk

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:02<00:22,  2.46s/it]

Depth level finished: 1: 1 URLs crawled; 0 files downloaded; 56 URLs in to_crawl_urls; 6 URLs in dont_crawl_urls

 20%|██        | 2/10 [01:36<07:31, 56.45s/it]

Depth level finished: 2: 27 URLs crawled; 0 files downloaded; 400 URLs in to_crawl_urls; 70 URLs in dont_crawl_urls

 30%|███       | 3/10 [02:51<07:33, 64.74s/it]

Depth level finished: 3: 38 URLs crawled; 11 files downloaded; 65 URLs in to_crawl_urls; 138 URLs in dont_crawl_urls

 40%|████      | 4/10 [05:01<09:04, 90.72s/it]

Depth level finished: 4: 67 URLs crawled; 11 files downloaded; 268 URLs in to_crawl_urls; 199 URLs in dont_crawl_urls

 50%|█████     | 5/10 [06:03<06:41, 80.24s/it]

Depth level finished: 5: 76 URLs crawled; 19 files downloaded; 23 URLs in to_crawl_urls; 272 URLs in dont_crawl_urls

 60%|██████    | 6/10 [07:28<05:27, 81.85s/it]

Depth level finished: 6: 94 URLs crawled; 20 files downloaded; 125 URLs in to_crawl_urls; 320 URLs in dont_crawl_urls
Batch 1 saved to disk

 70%|███████   | 7/10 [09:08<04:23, 87.77s/it]

Depth level finished: 7: 107 URLs crawled; 34 files downloaded; 38 URLs in to_crawl_urls; 383 URLs in dont_crawl_urls

 80%|████████  | 8/10 [11:38<03:35, 107.52s/it]

Depth level finished: 8: 131 URLs crawled; 34 files downloaded; 23 URLs in to_crawl_urls; 449 URLs in dont_crawl_urls

 90%|█████████ | 9/10 [13:17<01:45, 105.00s/it]

Depth level finished: 9: 153 URLs crawled; 35 files downloaded; 7 URLs in to_crawl_urls; 495 URLs in dont_crawl_urls

100%|██████████| 10/10 [13:46<00:00, 82.64s/it]

Depth level finished: 10: 159 URLs crawled; 36 files downloaded; 2 URLs in to_crawl_urls; 509 URLs in dont_crawl_urls

 30%|███       | 3/10 [33:46<1:22:05, 703.67s/it]

Batch 3 saved to disk

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:11<01:44, 11.60s/it]

Depth level finished: 1: 1 URLs crawled; 0 files downloaded; 40 URLs in to_crawl_urls; 6 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 20%|██        | 2/10 [04:16<19:48, 148.56s/it]

Depth level finished: 2: 25 URLs crawled; 0 files downloaded; 346 URLs in to_crawl_urls; 72 URLs in dont_crawl_urls

 30%|███       | 3/10 [05:04<12:01, 103.04s/it]

Depth level finished: 3: 31 URLs crawled; 0 files downloaded; 55 URLs in to_crawl_urls; 156 URLs in dont_crawl_urls

 40%|████      | 4/10 [07:44<12:31, 125.23s/it]

Depth level finished: 4: 46 URLs crawled; 0 files downloaded; 81 URLs in to_crawl_urls; 231 URLs in dont_crawl_urls

 50%|█████     | 5/10 [10:20<11:22, 136.60s/it]

Depth level finished: 5: 62 URLs crawled; 0 files downloaded; 66 URLs in to_crawl_urls; 305 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 60%|██████    | 6/10 [13:24<10:10, 152.66s/it]

Depth level finished: 6: 82 URLs crawled; 0 files downloaded; 84 URLs in to_crawl_urls; 375 URLs in dont_crawl_urls

 70%|███████   | 7/10 [17:47<09:26, 188.74s/it]

Depth level finished: 7: 109 URLs crawled; 0 files downloaded; 156 URLs in to_crawl_urls; 438 URLs in dont_crawl_urls
Batch 1 saved to disk

 80%|████████  | 8/10 [21:56<06:55, 207.79s/it]

Depth level finished: 8: 133 URLs crawled; 0 files downloaded; 129 URLs in to_crawl_urls; 504 URLs in dont_crawl_urls

 90%|█████████ | 9/10 [27:36<04:09, 249.05s/it]

Depth level finished: 9: 163 URLs crawled; 0 files downloaded; 195 URLs in to_crawl_urls; 564 URLs in dont_crawl_urls

100%|██████████| 10/10 [33:17<00:00, 199.73s/it]

Depth level finished: 10: 192 URLs crawled; 0 files downloaded; 213 URLs in to_crawl_urls; 625 URLs in dont_crawl_urls

 40%|████      | 4/10 [1:07:04<2:01:29, 1214.88s/it]

Batch 2 saved to disk

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:19<00:00, 19.92s/it]

Depth level finished: 1: 5 URLs crawled; 0 files downloaded; 126 URLs in to_crawl_urls; 11 URLs in dont_crawl_urls

 50%|█████     | 5/10 [1:07:25<1:05:20, 784.18s/it]

Batch 1 saved to disk

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:12<01:50, 12.28s/it]

Depth level finished: 1: 1 URLs crawled; 0 files downloaded; 40 URLs in to_crawl_urls; 6 URLs in dont_crawl_urls

 20%|██        | 2/10 [04:53<22:43, 170.39s/it]

Depth level finished: 2: 26 URLs crawled; 0 files downloaded; 345 URLs in to_crawl_urls; 71 URLs in dont_crawl_urls

 30%|███       | 3/10 [05:29<12:44, 109.25s/it]

Depth level finished: 3: 30 URLs crawled; 0 files downloaded; 47 URLs in to_crawl_urls; 157 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 40%|████      | 4/10 [07:09<10:32, 105.48s/it]

Depth level finished: 4: 42 URLs crawled; 0 files downloaded; 57 URLs in to_crawl_urls; 235 URLs in dont_crawl_urls

 50%|█████     | 5/10 [09:24<09:40, 116.15s/it]

Depth level finished: 5: 62 URLs crawled; 0 files downloaded; 88 URLs in to_crawl_urls; 305 URLs in dont_crawl_urls

 60%|██████    | 6/10 [12:20<09:06, 136.53s/it]

Depth level finished: 6: 89 URLs crawled; 0 files downloaded; 123 URLs in to_crawl_urls; 368 URLs in dont_crawl_urls

 70%|███████   | 7/10 [15:01<07:13, 144.55s/it]

Depth level finished: 7: 110 URLs crawled; 0 files downloaded; 103 URLs in to_crawl_urls; 437 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 80%|████████  | 8/10 [18:40<05:36, 168.28s/it]

Depth level finished: 8: 138 URLs crawled; 0 files downloaded; 124 URLs in to_crawl_urls; 499 URLs in dont_crawl_urls
Batch 1 saved to disk

 90%|█████████ | 9/10 [21:12<02:43, 163.18s/it]

Depth level finished: 9: 159 URLs crawled; 0 files downloaded; 136 URLs in to_crawl_urls; 568 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

100%|██████████| 10/10 [23:40<00:00, 142.03s/it]

Depth level finished: 10: 178 URLs crawled; 0 files downloaded; 126 URLs in to_crawl_urls; 639 URLs in dont_crawl_urls

 60%|██████    | 6/10 [1:31:06<1:06:43, 1000.80s/it]

Batch 3 saved to disk

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:03<00:32,  3.66s/it]

Depth level finished: 1: 1 URLs crawled; 0 files downloaded; 48 URLs in to_crawl_urls; 6 URLs in dont_crawl_urls

 20%|██        | 2/10 [01:27<06:48, 51.02s/it]

Depth level finished: 2: 26 URLs crawled; 0 files downloaded; 523 URLs in to_crawl_urls; 71 URLs in dont_crawl_urls

 30%|███       | 3/10 [02:31<06:39, 57.02s/it]

Depth level finished: 3: 46 URLs crawled; 0 files downloaded; 349 URLs in to_crawl_urls; 141 URLs in dont_crawl_urls

 40%|████      | 4/10 [03:32<05:50, 58.41s/it]

Depth level finished: 4: 64 URLs crawled; 1 files downloaded; 237 URLs in to_crawl_urls; 212 URLs in dont_crawl_urls

 50%|█████     | 5/10 [04:48<05:22, 64.57s/it]

Depth level finished: 5: 87 URLs crawled; 2 files downloaded; 338 URLs in to_crawl_urls; 278 URLs in dont_crawl_urls
Batch 1 saved to disk

 60%|██████    | 6/10 [06:01<04:29, 67.50s/it]

Depth level finished: 6: 110 URLs crawled; 2 files downloaded; 216 URLs in to_crawl_urls; 345 URLs in dont_crawl_urls

 70%|███████   | 7/10 [07:19<03:33, 71.04s/it]

Depth level finished: 7: 135 URLs crawled; 3 files downloaded; 193 URLs in to_crawl_urls; 409 URLs in dont_crawl_urls

 80%|████████  | 8/10 [08:31<02:22, 71.33s/it]

Depth level finished: 8: 157 URLs crawled; 6 files downloaded; 210 URLs in to_crawl_urls; 474 URLs in dont_crawl_urls

 90%|█████████ | 9/10 [12:10<01:57, 117.54s/it]

Depth level finished: 9: 179 URLs crawled; 8 files downloaded; 163 URLs in to_crawl_urls; 540 URLs in dont_crawl_urls

100%|██████████| 10/10 [13:13<00:00, 79.38s/it]

Depth level finished: 10: 200 URLs crawled; 8 files downloaded; 202 URLs in to_crawl_urls; 609 URLs in dont_crawl_urls

 70%|███████   | 7/10 [1:44:21<46:40, 933.46s/it]

Batch 2 saved to disk

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:03<00:35,  3.91s/it]

Depth level finished: 1: 1 URLs crawled; 0 files downloaded; 29 URLs in to_crawl_urls; 6 URLs in dont_crawl_urls

 20%|██        | 2/10 [01:06<05:05, 38.16s/it]

Depth level finished: 2: 17 URLs crawled; 0 files downloaded; 271 URLs in to_crawl_urls; 77 URLs in dont_crawl_urls

 30%|███       | 3/10 [01:53<04:57, 42.52s/it]

Depth level finished: 3: 27 URLs crawled; 14 files downloaded; 157 URLs in to_crawl_urls; 143 URLs in dont_crawl_urls

100%|██████████| 10/10 [02:22<00:00, 14.22s/it][A

Depth level finished: 4: 44 URLs crawled; 14 files downloaded; 0 URLs in to_crawl_urls; 215 URLs in dont_crawl_urls
Depth level finished: 5: 44 URLs crawled; 14 files downloaded; 0 URLs in to_crawl_urls; 215 URLs in dont_crawl_urls
Depth level finished: 6: 44 URLs crawled; 14 files downloaded; 0 URLs in to_crawl_urls; 215 URLs in dont_crawl_urls
Depth level finished: 7: 44 URLs crawled; 14 files downloaded; 0 URLs in to_crawl_urls; 215 URLs in dont_crawl_urls
Depth level finished: 8: 44 URLs crawled; 14 files downloaded; 0 URLs in to_crawl_urls; 215 URLs in dont_crawl_urls
Depth level finished: 9: 44 URLs crawled; 14 files downloaded; 0 URLs in to_crawl_urls; 215 URLs in dont_crawl_urls
Depth level finished: 10: 44 URLs crawled; 14 files downloaded; 0 URLs in to_crawl_urls; 215 URLs in dont_crawl_urls

 80%|████████  | 8/10 [1:46:44<22:43, 681.79s/it]

Batch 1 saved to disk

  0%|          | 0/10 [00:00<?, ?it/s]Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 10%|█         | 1/10 [00:03<00:27,  3.01s/it]

Depth level finished: 1: 1 URLs crawled; 0 files downloaded; 92 URLs in to_crawl_urls; 6 URLs in dont_crawl_urls

connection unexpectedly closed
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 20%|██        | 2/10 [00:54<04:10, 31.27s/it]

Depth level finished: 2: 23 URLs crawled; 0 files downloaded; 233 URLs in to_crawl_urls; 74 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 30%|███       | 3/10 [01:43<04:35, 39.38s/it]

Depth level finished: 3: 39 URLs crawled; 0 files downloaded; 235 URLs in to_crawl_urls; 148 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 40%|████      | 4/10 [03:16<06:03, 60.57s/it]

Depth level finished: 4: 63 URLs crawled; 0 files downloaded; 284 URLs in to_crawl_urls; 214 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 50%|█████     | 5/10 [04:35<05:37, 67.41s/it]

Depth level finished: 5: 85 URLs crawled; 0 files downloaded; 212 URLs in to_crawl_urls; 280 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

Batch 1 saved to disk

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 60%|██████    | 6/10 [05:51<04:40, 70.19s/it]

Depth level finished: 6: 105 URLs crawled; 0 files downloaded; 201 URLs in to_crawl_urls; 349 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 70%|███████   | 7/10 [07:03<03:32, 70.86s/it]

Depth level finished: 7: 127 URLs crawled; 0 files downloaded; 204 URLs in to_crawl_urls; 417 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 80%|████████  | 8/10 [08:26<02:29, 74.85s/it]

Depth level finished: 8: 148 URLs crawled; 0 files downloaded; 195 URLs in to_crawl_urls; 486 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

 90%|█████████ | 9/10 [09:47<01:16, 76.52s/it]

Depth level finished: 9: 171 URLs crawled; 0 files downloaded; 295 URLs in to_crawl_urls; 551 URLs in dont_crawl_urls

Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.

100%|██████████| 10/10 [10:38<00:00, 63.82s/it]

Depth level finished: 10: 185 URLs crawled; 0 files downloaded; 179 URLs in to_crawl_urls; 626 URLs in dont_crawl_urls

 90%|█████████ | 9/10 [1:57:24<11:08, 668.68s/it]

Batch 2 saved to disk

  0%|          | 0/10 [00:00<?, ?it/s]
 10%|█         | 1/10 [00:02<00:21,  2.34s/it]

Depth level finished: 1: 1 URLs crawled; 0 files downloaded; 50 URLs in to_crawl_urls; 117 URLs in dont_crawl_urls

 20%|██        | 2/10 [01:46<08:16, 62.08s/it]

Depth level finished: 2: 28 URLs crawled; 0 files downloaded; 304 URLs in to_crawl_urls; 180 URLs in dont_crawl_urls

 30%|███       | 3/10 [02:44<07:02, 60.42s/it]

Depth level finished: 3: 49 URLs crawled; 0 files downloaded; 328 URLs in to_crawl_urls; 247 URLs in dont_crawl_urls

 40%|████      | 4/10 [03:20<05:04, 50.75s/it]

Depth level finished: 4: 63 URLs crawled; 0 files downloaded; 308 URLs in to_crawl_urls; 322 URLs in dont_crawl_urls

 50%|█████     | 5/10 [03:52<03:40, 44.00s/it]

Depth level finished: 5: 75 URLs crawled; 0 files downloaded; 238 URLs in to_crawl_urls; 400 URLs in dont_crawl_urls

 60%|██████    | 6/10 [05:00<03:27, 51.99s/it]

Depth level finished: 6: 99 URLs crawled; 0 files downloaded; 363 URLs in to_crawl_urls; 466 URLs in dont_crawl_urls
Batch 1 saved to disk

 70%|███████   | 7/10 [06:05<02:49, 56.43s/it]

Depth level finished: 7: 123 URLs crawled; 0 files downloaded; 310 URLs in to_crawl_urls; 532 URLs in dont_crawl_urls

 80%|████████  | 8/10 [07:13<02:00, 60.05s/it]

Depth level finished: 8: 149 URLs crawled; 0 files downloaded; 356 URLs in to_crawl_urls; 596 URLs in dont_crawl_urls

 90%|█████████ | 9/10 [08:15<01:00, 60.73s/it]

Depth level finished: 9: 172 URLs crawled; 0 files downloaded; 281 URLs in to_crawl_urls; 661 URLs in dont_crawl_urls

100%|██████████| 10/10 [09:17<00:00, 55.74s/it]

Depth level finished: 10: 194 URLs crawled; 0 files downloaded; 359 URLs in to_crawl_urls; 729 URLs in dont_crawl_urls

100%|██████████| 10/10 [2:06:43<00:00, 760.32s/it]

Batch 2 saved to disk

## Read local crawl results

In [12]:
# crawl_data_path  = ("/Users/stephengodfrey/OneDrive - numanticsolutions.com"
#                     "/Engagements/Projects/ccc_policy_assistant/data/crawls")


crawl_data_path = "ecs"
crawl_file = "enwikipediaorg_2024Dec11_10.csv"
crawl_file = 'laocagov_2024Dec17_1.csv'
crawl_file = "wwwccleagueorg_2024Dec17_1.csv"
crawl_file = "wwwecsorg_2025Feb04_1.csv"


gcp_project_id = "eternal-bongo-435614-b9"
gcs_bucket_name = "webfiles-test"

# Create a storage client
storage_client = storage.Client(project=gcp_project_id)

# Get the bucket
bucket = storage_client.bucket(gcs_bucket_name)

# Get the blob
blob = bucket.blob(os.path.join(crawl_data_path, crawl_file))


# gcs_directory=df_cp.loc[9, "storage_folder"]
# res_filename = "test.csv"
# blob = bucket.blob(os.path.join("{}/crawls/".format(gcs_directory), res_filename))
# blob = bucket.blob(gcs_directory, res_filename)
# blob.upload_from_string(df.to_csv(), 'text/csv')

# Download the file as a string




# Read the CSV string into a DataFrame
# Not working
# csv_string = blob.download_as_string()
# dft = pd.read_csv(io.StringIO(csv_string))

# Works
data = blob.download_as_bytes()
dft = pd.read_csv(io.BytesIO(data))



# dft = pd.read_csv(filepath_or_buffer=os.path.join(crawl_data_path,crawl_file))

In [10]:
os.path.join("{}/crawls/".format(gcs_directory))

gcs_directory=df_cp.loc[9, "storage_folder"]

gcs_directory

'ecs'

In [19]:
# dft.loc[0,'seed_url']
# dft.loc[0,'ptag_text']

dft

# for idx in dft.index:
#     print(dft.loc[idx, "url"])
#     print(dft.loc[idx, "ptag_text"])
#     print()

# dft.loc[0,"ptag_text"]  == dft.loc[1,"ptag_text"]
# dft.loc[1,"ptag_text"]  == dft.loc[2,"ptag_text"]

,Unnamed: 0,seed_url,url,html_code_string,ptag_text,atag_urls,crawl_time
0,0,https://www.ecs.org,https://www.ecs.org,"<!DOCTYPE html>\n<html class=""ghostkit-effects...",Resources by Topic Resources by State Trending...,"['https://www.ecs.org/blog/', 'https://www.ecs...",2025-02-04 17:00:01
1,1,https://www.ecs.org,https://www.ecs.org#dropdown,"<!DOCTYPE html>\n<html class=""ghostkit-effects...",Resources by Topic Resources by State Trending...,"['https://www.ecs.org/blog/', 'https://www.ecs...",2025-02-04 17:00:03
2,2,https://www.ecs.org,https://www.ecs.org/blog/,"<!DOCTYPE html>\n<html class=""ghostkit-effects...",Resources by Topic Resources by State Trending...,"['https://www.ecs.org/ecs-events/', 'https://w...",2025-02-04 17:00:06
3,3,https://www.ecs.org,https://www.ecs.org/ecs-events/,"<!DOCTYPE html>\n<html class=""ghostkit-effects...",Resources by Topic Resources by State Trending...,"['https://www.ecs.org/ecs-events/', 'https://w...",2025-02-04 17:00:08
4,4,https://www.ecs.org,https://www.ecs.org/blog/#dropdown,"<!DOCTYPE html>\n<html class=""ghostkit-effects...",Resources by Topic Resources by State Trending...,"['https://www.ecs.org/ecs-events/', 'https://w...",2025-02-04 17:00:10
5,5,https://www.ecs.org,https://www.ecs.org/ecs-events/#dropdown,"<!DOCTYPE html>\n<html class=""ghostkit-effects...",Resources by Topic Resources by State Trending...,"['https://www.ecs.org/ecs-events/', 'https://w...",2025-02-04 17:00:12

## Save results to BigQuery

In [ ]:
# Identify the table; note the database.table naming schema
table_id = "ccc_polasst.crawl_data"
table_id = "ccc_polasst.crawl_data_tes"
project_id = "eternal-bongo-435614-b9"

# Use Pandas-gbq to write to the BQ table
if_exists = "replace"
# if_exists = "append"

# pandas_gbq.to_gbq(dataframe=df, destination_table=table_id,
#                   project_id=project_id, if_exists=if_exists)