# Summary

## Test a BigQuery connection

In [1]:
import os

import pandas as pd

# Helpful library for reading and writing data: BQ to Pandas
# https://pandas-gbq.readthedocs.io/en/latest/
import pandas_gbq

## Authentication

In [2]:
# path to GCP credentials file
creds_file_path = "../data/environment"
# os.listdir(creds_file_path)
creds_file = "eternal-bongo-435614-b9-bf6a5e630e44.json"

# Set an environment variable
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = os.path.join(creds_file_path, creds_file)

GOOGLE_CLOUD_PROJECT="eternal-bongo-435614-b9"

# Load with bigquery client

In [3]:
from google.cloud import bigquery

# Create a BigQuery client
client = bigquery.Client(project=GOOGLE_CLOUD_PROJECT)

# table_name = "bigquery-public-data.america_health_rankings.ahr"
table_name = "ipeds.al2023"

query = ("SELECT *  FROM {} LIMIT 10").format(table_name)
print(query)

query_job = client.query(query)

df = query_job.to_dataframe()
df

SELECT *  FROM ipeds.al2023 LIMIT 10

/opt/anaconda3/envs/google-adk/lib/python3.11/site-packages/google/cloud/bigquery/table.py:1933: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,UNITID,LEXP100K,LCOLELYN,XLPBOOKS,LPBOOKS,XLEBOOKS,LEBOOKS,XLEDATAB,LEDATAB,XLPMEDIA,...,XLEXOMPS,LEXOMPS,XLEXOMOT,LEXOMOT,XLEXOMTL,LEXOMTL,XLEXPTOT,LEXPTOT,LSWMSOM,college_name
0,108667,1,2,R,13360.0,R,200,R,35,R,...,R,0.0,R,0.0,R,0.0,R,1012590.0,722590,COLLEGE OF ALAMEDA
1,109819,1,2,R,73080.0,R,10760,R,100,R,...,R,0.0,R,9800.0,R,9800.0,R,1195707.0,978376,BAKERSFIELD COLLEGE
2,109907,1,2,R,18059.0,R,71806,R,13,R,...,R,0.0,R,3460.0,R,3460.0,R,548800.0,402791,BARSTOW COMMUNITY COLLEGE
3,111434,1,2,R,35421.0,R,945,R,86,R,...,R,0.0,R,2695.0,R,2695.0,R,1064880.0,811199,CANADA COLLEGE
4,111920,1,2,R,40636.0,R,111428,R,87,R,...,R,0.0,R,18600.0,R,18600.0,R,1821687.0,1255992,CHABOT COLLEGE
5,111939,1,2,R,88070.0,R,189787,Z,0,R,...,R,0.0,R,58012.0,R,58012.0,R,2208057.0,1902753,CHAFFEY COLLEGE
6,112172,1,2,R,33894.0,R,322871,R,44,R,...,R,497.0,R,41292.0,R,41789.0,R,1547591.0,1080578,CITRUS COLLEGE
7,112190,1,2,R,105927.0,R,295000,R,47,R,...,R,0.0,R,597374.0,R,597374.0,R,6036307.0,4517115,CITY COLLEGE OF SAN FRANCISCO
8,112686,1,2,R,44405.0,R,250250,R,35,R,...,R,0.0,R,108871.0,R,108871.0,R,760041.0,565321,COMPTON COLLEGE
9,114266,1,2,R,43380.0,R,13697,R,41,R,...,R,951.0,R,22618.0,R,23569.0,R,1429236.0,977250,EVERGREEN VALLEY COLLEGE

# Read with Pandas GBP

In [4]:
df = pandas_gbq.read_gbq(query_or_table=query,
                         project_id=GOOGLE_CLOUD_PROJECT)
df

Downloading: 100%|██████████|

,UNITID,LEXP100K,LCOLELYN,XLPBOOKS,LPBOOKS,XLEBOOKS,LEBOOKS,XLEDATAB,LEDATAB,XLPMEDIA,...,XLEXOMPS,LEXOMPS,XLEXOMOT,LEXOMOT,XLEXOMTL,LEXOMTL,XLEXPTOT,LEXPTOT,LSWMSOM,college_name
0,108667,1,2,R,13360.0,R,200,R,35,R,...,R,0.0,R,0.0,R,0.0,R,1012590.0,722590,COLLEGE OF ALAMEDA
1,109819,1,2,R,73080.0,R,10760,R,100,R,...,R,0.0,R,9800.0,R,9800.0,R,1195707.0,978376,BAKERSFIELD COLLEGE
2,109907,1,2,R,18059.0,R,71806,R,13,R,...,R,0.0,R,3460.0,R,3460.0,R,548800.0,402791,BARSTOW COMMUNITY COLLEGE
3,111434,1,2,R,35421.0,R,945,R,86,R,...,R,0.0,R,2695.0,R,2695.0,R,1064880.0,811199,CANADA COLLEGE
4,111920,1,2,R,40636.0,R,111428,R,87,R,...,R,0.0,R,18600.0,R,18600.0,R,1821687.0,1255992,CHABOT COLLEGE
5,111939,1,2,R,88070.0,R,189787,Z,0,R,...,R,0.0,R,58012.0,R,58012.0,R,2208057.0,1902753,CHAFFEY COLLEGE
6,112172,1,2,R,33894.0,R,322871,R,44,R,...,R,497.0,R,41292.0,R,41789.0,R,1547591.0,1080578,CITRUS COLLEGE
7,112190,1,2,R,105927.0,R,295000,R,47,R,...,R,0.0,R,597374.0,R,597374.0,R,6036307.0,4517115,CITY COLLEGE OF SAN FRANCISCO
8,112686,1,2,R,44405.0,R,250250,R,35,R,...,R,0.0,R,108871.0,R,108871.0,R,760041.0,565321,COMPTON COLLEGE
9,114266,1,2,R,43380.0,R,13697,R,41,R,...,R,951.0,R,22618.0,R,23569.0,R,1429236.0,977250,EVERGREEN VALLEY COLLEGE

## Change GCP credentials

In [5]:
# path to GCP credentials file
creds_file_path = "../data/environment"
# os.listdir(creds_file_path)
creds_file = "eternal-bongo-435614-b9-0127167e0d20.json"

# Set an environment variable
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = os.path.join(creds_file_path, creds_file)

GOOGLE_CLOUD_PROJECT="eternal-bongo-435614-b9"

In [6]:
# table_name = "bigquery-public-data.america_health_rankings.ahr"
table_name = "ipeds.al2023"

query = ("SELECT *  FROM {} LIMIT 10").format(table_name)
print(query)

df = pandas_gbq.read_gbq(query_or_table=query,
                         project_id=GOOGLE_CLOUD_PROJECT)
df

SELECT *  FROM ipeds.al2023 LIMIT 10
Downloading: 100%|██████████|

,UNITID,LEXP100K,LCOLELYN,XLPBOOKS,LPBOOKS,XLEBOOKS,LEBOOKS,XLEDATAB,LEDATAB,XLPMEDIA,...,XLEXOMPS,LEXOMPS,XLEXOMOT,LEXOMOT,XLEXOMTL,LEXOMTL,XLEXPTOT,LEXPTOT,LSWMSOM,college_name
0,108667,1,2,R,13360.0,R,200,R,35,R,...,R,0.0,R,0.0,R,0.0,R,1012590.0,722590,COLLEGE OF ALAMEDA
1,109819,1,2,R,73080.0,R,10760,R,100,R,...,R,0.0,R,9800.0,R,9800.0,R,1195707.0,978376,BAKERSFIELD COLLEGE
2,109907,1,2,R,18059.0,R,71806,R,13,R,...,R,0.0,R,3460.0,R,3460.0,R,548800.0,402791,BARSTOW COMMUNITY COLLEGE
3,111434,1,2,R,35421.0,R,945,R,86,R,...,R,0.0,R,2695.0,R,2695.0,R,1064880.0,811199,CANADA COLLEGE
4,111920,1,2,R,40636.0,R,111428,R,87,R,...,R,0.0,R,18600.0,R,18600.0,R,1821687.0,1255992,CHABOT COLLEGE
5,111939,1,2,R,88070.0,R,189787,Z,0,R,...,R,0.0,R,58012.0,R,58012.0,R,2208057.0,1902753,CHAFFEY COLLEGE
6,112172,1,2,R,33894.0,R,322871,R,44,R,...,R,497.0,R,41292.0,R,41789.0,R,1547591.0,1080578,CITRUS COLLEGE
7,112190,1,2,R,105927.0,R,295000,R,47,R,...,R,0.0,R,597374.0,R,597374.0,R,6036307.0,4517115,CITY COLLEGE OF SAN FRANCISCO
8,112686,1,2,R,44405.0,R,250250,R,35,R,...,R,0.0,R,108871.0,R,108871.0,R,760041.0,565321,COMPTON COLLEGE
9,114266,1,2,R,43380.0,R,13697,R,41,R,...,R,951.0,R,22618.0,R,23569.0,R,1429236.0,977250,EVERGREEN VALLEY COLLEGE